### ISSUE TITLE
Feature Request - Dual Solution Computation and Termination

### ISSUE THREAD

**Issue by MassimoDeMauri** [Benny44/QPALM#3]
In mixed integer applications, it would be great to get as output the dual objective of the current solution. Moreover, an useful feature would be the possibility of stopping the algorithm as soon as the dual solution is above a certain threshold.

**Comment by Benny44** [comment]
Hey Massimo,
I added this feature in the latest merge with master. 
Set settings->enable_dual_termination = TRUE;
and settings->dual_objective_limit = the value you wish to stop at (default = +inf).

The dual objective function (which together with the primal objective is now also returned along in info) will only by computed when enable_dual_termination = TRUE, so use this from the beginning.

Best,
Ben
