### ISSUE TITLE
Problem compiling the mex interface

### ISSUE THREAD

**Issue by sunju** [Benny44/QPALM#7]
Dear QPALM team, 

When running qpalm_setup.m, I encountered the error attached at the end. 
It seems in the header file, qpalm_setup is defined to take in two parameters, whereas qpalm_setup inside qpalm_setup is taking a third parameter &c. 

===== 
`...............................Error using mex
/home/sun/Downloads/QPALM/interfaces/mex/qpalm_mex.c: In function ‘mexFunction’:
/home/sun/Downloads/QPALM/interfaces/mex/qpalm_mex.c:189:22: error: too many arguments to function
‘qpalm_setup’
  189 |         qpalm_work = qpalm_setup(data, settings, &c);
      |                      ^~~~~~~~~~~
In file included from /home/sun/Downloads/QPALM/interfaces/mex/qpalm_mex.c:4:
../../include/qpalm.h:47:17: note: declared here
   47 | QPALMWorkspace* qpalm_setup(const QPALMData     *data,
      |                 ^~~~~~~~~~~

Error in qpalm_make>do_cmd (line 403)
eval (s) ;

Error in qpalm_make (line 369)
kk = do_cmd (s, kk, details) ;`

**Comment by Benny44** [comment]
Thank you for notifying us! This issue should have been fixed now with this commit 66c86f4a19bf17eab393e0cda25b3c287e388cf0. Let me know if any issue persists.

**Comment by sunju** [comment]
Thank you for the quick fix! Compiling goes through now and the mex examples are working well.

**Comment by Benny44** [comment]
You're welcome!
